spring.application.name=auction-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/rostra_auction
spring.datasource.username=rostra
spring.datasource.password=rostra_dev_pw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=lSr+b8Q69GkkZWtPaUfIPmaxMaOJhy3V8SqD93Y/+nY=

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

app.kafka.topics.auction-ended=auction.ended

springdoc.swagger-ui.path=/swagger-ui.html

spring.task.scheduling.pool.size=2