spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/rostra_auth
spring.datasource.username=rostra
spring.datasource.password=rostra_dev_pw
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=lSr+b8Q69GkkZWtPaUfIPmaxMaOJhy3V8SqD93Y/+nY=
app.jwt.access-token-expiry-ms=900000

app.refresh-token.expiry-days=7
app.refresh-token.rotate=true

app.cookie.secure=false
app.cookie.same-site=Strict
app.cookie.max-age-seconds=604800